version: "2"

networks:
  proxy:
    external: true

services:
  njsp1:
    build: .
    networks:
      - proxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.njsp1.rule=Host(`njsp1.muldoon.eu`)"
      - "traefik.http.routers.njsp1.entrypoints=websecure"
      - "traefik.http.routers.njsp1.tls.certresolver=letsencrypt"
      - "traefik.http.services.njsp1.loadbalancer.server.port=3000" # facultative (traefik will use the first exposed port by default)
      - "traefik.http.routers.njsp1.tls=true"